server:
  port: 9192

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goibibo
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql:true
    database: postgresql
  servlet:
    multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    file-size-threshold: 2KB